function params = designParameters()
%DESIGNPARAMETERS Edit this file, then run performance.m.
% Sweep angles are degrees. Vehicle and engine code convert them to radians.
% Published engine altitude and Mach limits are not applied. The maps keep
% every point the cycle and drag build-up can calculate.

params.engineNames = [
    "PBS TJ40-G1"
    "AMT Olympus 23"
    "AMT NL NIKE HP"
    "AMT NL Pegasus HP"
    "AMT Olympus HP"
    ].';

params.machGrid = linspace(0, 1.1, 60);
params.altitudeGrid_m = linspace(0, 11000, 50);

% Nearest grid points to these conditions are printed as a table.
params.reportMach = [0.80 0.95 1.05];
params.reportAltitude_m = [0 5000 8000];

params.cycle = localCycleParameters();
params.vehicle = localVehicleDesign();
end

function cycle = localCycleParameters()
% One-point turbojet. Sea-level static thrust and fuel are anchored to the
% catalog after the cycle is evaluated, so these efficiencies set the lapse
% with Mach and altitude rather than the static point.
%
% Corrected flow and OPR stay at the catalog point while inlet total
% temperature is at or below the sea-level static value. Above that, a fixed
% physical redline drops corrected flow and OPR. Set both redline exponents
% to 0 to hold OPR and corrected flow constant everywhere.
cycle = struct( ...
    "CompressorIsentropicEfficiency", 0.78, ...
    "TurbineIsentropicEfficiency", 0.84, ...
    "MechanicalEfficiency", 0.98, ...
    "BurnerEfficiency", 0.98, ...
    "BurnerPressureRatio", 0.95, ...
    "NozzleKineticEfficiency", 0.97, ...
    "InletPressureRecovery", 0.97, ...
    "SupersonicRecoveryCoefficient", 0.075, ...
    "SupersonicRecoveryExponent", 1.35, ...
    "RedlineFlowExponent", 1.0, ...
    "RedlinePressureExponent", 2.0, ...
    "FuelHeatingValue_J_kg", 43.2e6, ...
    "ColdGamma", 1.40, ...
    "HotGamma", 1.33, ...
    "GasConstant_J_kgK", 287.05287, ...
    "FuelFlowDisagreementTolerance", 0.05);
end

function vehicle = localVehicleDesign()
% Level flight uses MaximumTakeoffMass_kg for every engine. Mass fraction is
% handled outside this model. FuselageDiameter_m = NaN sizes the body to the
% engine diameter. TailQuarterChordSweep_deg = NaN uses the wing sweep.
vehicle = struct( ...
    "MaximumTakeoffMass_kg", 25, ...
    "EngineCount", 1, ...
    "ReferenceArea_m2", 0.25, ...
    "WingSpan_m", 0.5, ...
    "WingTaperRatio", 0.5, ...
    "WingExposedAreaFraction", 0.95, ...
    "WingThicknessToChord", 0.03, ...
    "WingMaxThicknessLocationChord", 0.50, ...
    "WingQuarterChordSweep_deg", 70, ...
    "TailToWingWettedRatio", 0.30, ...
    "TailChordOverMeanAerodynamicChord", 0.45, ...
    "TailThicknessToChord", 0.03, ...
    "TailMaxThicknessLocationChord", 0.30, ...
    "TailQuarterChordSweep_deg", NaN, ...
    "TailInterferenceFactor", 1.05, ...
    "FuselageLength_m", 1.5, ...
    "FuselageDiameter_m", NaN, ...
    "FuselageToEngineDiameterRatio", 1.1, ...
    "FuselageVolumeFill", 0.70, ...
    "WingVolumeFill", 0.50, ...
    "OswaldEfficiency", 0.60, ...
    "WingInterferenceFactor", 1.0, ...
    "FuselageInterferenceFactor", 1.0, ...
    "ExcrescenceFactor", 1.15, ...
    "KornTechnologyFactor", 0.91, ...
    "DragCreepMachOffset", 0.08, ...
    "LockRiseCoefficient", 20, ...
    "WingWaveDragCapFactor", 8, ...
    "WaveDragFactor", 1.4, ...
    "VolumeWaveOnsetNumerator", 0.80, ...
    "VolumeWaveMachFull", 1.15, ...
    "FormFactorMachCap", 0.85, ...
    "Notes", "Edit designParameters.m and rerun performance.m.");
end
