function vehicles = definePlaceholderVehicle(engines)
%DEFINEPLACEHOLDERVEHICLE Return first-cut vehicle variants for each engine.
% All dimensional values are SI. S_ref is the wing planform area.

arguments
    engines (1,:) struct
end

vehicles = repmat(localBaseVehicle(), 1, numel(engines));

for iVehicle = 1:numel(engines)
    engine = engines(iVehicle);
    vehicle = localBaseVehicle();

    engineDiameter_m = engine.OuterDiameter_m;
    if ~isfinite(engineDiameter_m)
        engineDiameter_m = 0.15;
    end

    vehicle.Name = "Vehicle with " + engine.Name;
    vehicle.EngineName = engine.Name;
    vehicle.EngineOuterDiameter_m = engineDiameter_m;
    vehicle.FuselageDiameter_m = 1.1 * engineDiameter_m;
    vehicle.FuselageFrontalArea_m2 = vehicle.EngineCount * ...
        pi * (vehicle.FuselageDiameter_m / 2)^2;
    vehicle.FuselageFinenessRatio = vehicle.FuselageLength_m / ...
        vehicle.FuselageDiameter_m;
    vehicle.AspectRatio = vehicle.WingSpan_m^2 / vehicle.ReferenceArea_m2;
    vehicle.WingExposedArea_m2 = vehicle.ReferenceArea_m2 * ...
        vehicle.WingExposedAreaFraction;
    vehicle.WingWettedArea_m2 = 2.0 * vehicle.WingExposedArea_m2 * ...
        (1 + 0.25 * vehicle.WingThicknessToChord);
    vehicle.FuselageWettedArea_m2 = pi * vehicle.FuselageDiameter_m * ...
        vehicle.FuselageLength_m;

    vehicles(iVehicle) = vehicle;
end
end

function vehicle = localBaseVehicle()
vehicle = struct( ...
    "Name", "Boom Prize Vehicle", ...
    "EngineName", "", ...
    "EngineCount", 2, ...
    "ReferenceArea_m2", 0.25, ...
    "WingPlanformArea_m2", 0.25, ...
    "WingSpan_m", 0.5, ...
    "MeanAerodynamicChord_m", 0.25, ...
    "AspectRatio", NaN, ...
    "WingExposedAreaFraction", 0.95, ...
    "WingExposedArea_m2", NaN, ...
    "WingWettedArea_m2", NaN, ...
    "WingThicknessToChord", 0.03, ...
    "WingMaxThicknessLocationChord", 0.5, ...
    "WingQuarterChordSweep_rad", 0.93, ...
    "FuselageLength_m", 1.0, ...
    "FuselageDiameter_m", NaN, ...
    "FuselageFrontalArea_m2", NaN, ...
    "FuselageFinenessRatio", NaN, ...
    "FuselageWettedArea_m2", NaN, ...
    "EngineOuterDiameter_m", NaN, ...
    "OswaldEfficiency", 0.6, ...
    "WingInterferenceFactor", 1.0, ...
    "FuselageInterferenceFactor", 1.3, ...
    "WingWaveDragScale", 8.0, ...
    "GrossMass_kg", 25.0, ...
    "Notes", "First-cut drag polar geometry");
end
