function engines = defineEngines(engineNames)
%DEFINEENGINES Return engine definition structs by name.
% Engine parameters are imported from boom_prize_design_engines.csv and
% stored using SI units only.

arguments
    engineNames (1,:) string
end

catalog = localEngineCatalog();
engines = repmat(localEmptyEngine(), 1, numel(engineNames));
catalogNames = [catalog.Name];

for iEngine = 1:numel(engineNames)
    name = engineNames(iEngine);
    matchIdx = find(strcmpi(catalogNames, name), 1);

    if isempty(matchIdx)
        error("defineEngines:UnknownEngine", ...
            "Unknown engine '%s'. Add it to localEngineCatalog().", name);
    end

    engines(iEngine) = catalog(matchIdx);
end
end

function catalog = localEngineCatalog()
csvPath = fullfile(fileparts(mfilename("fullpath")), ...
    "boom_prize_design_engines.csv");

opts = detectImportOptions(csvPath, "VariableNamingRule", "preserve");
rawEngines = readtable(csvPath, opts);

catalog = repmat(localEmptyEngine(), height(rawEngines), 1);

for iEngine = 1:height(rawEngines)
    maxThrust_N = localNumber(rawEngines.("max thrust (N)")(iEngine));
    installedThrust_N = localNumber(rawEngines.("installed thrust (N)")(iEngine));

    catalog(iEngine) = struct( ...
        "Option", localNumber(rawEngines.option(iEngine)), ...
        "Name", string(rawEngines.engine(iEngine)), ...
        "Type", "turbojet", ...
        "Architecture", string(rawEngines.architecture(iEngine)), ...
        "MaxThrust_N", maxThrust_N, ...
        "InstalledThrust_N", installedThrust_N, ...
        "IdleThrust_N", localNumber(rawEngines.("idle thrust (N)")(iEngine)), ...
        "SeaLevelStaticThrust_N", maxThrust_N, ...
        "InstalledSeaLevelStaticThrust_N", installedThrust_N, ...
        "DryMass_kg", localNumber(rawEngines.("dry weight (kg)")(iEngine)), ...
        "InstalledMass_kg", localNumber(rawEngines.("installed mass (kg)")(iEngine)), ...
        "ThrustToWeightEngineOnly", localNumber(rawEngines.("T/W engine-only")(iEngine)), ...
        "OuterDiameter_m", localNumber(rawEngines.("Outer diameter(mm)")(iEngine)) / 1000, ...
        "Length_m", localNumber(rawEngines.("length (mm)")(iEngine)) / 1000, ...
        "MaxAngularSpeed_rad_s", localRpmToRadPerSec(rawEngines.("max RPM")(iEngine)), ...
        "IdleAngularSpeed_rad_s", localRpmToRadPerSec(rawEngines.("idle RPM")(iEngine)), ...
        "OverallPressureRatio", localNumber(rawEngines.OPR(iEngine)), ...
        "ReferenceMassFlow_kg_s", localNumber(rawEngines.("mdot (kg/s)")(iEngine)), ...
        "FuelFlow_kg_s", localNumber(rawEngines.("fuel flow (kg/min)")(iEngine)) / 60, ...
        "SFC_kg_N_s", localNumber(rawEngines.("SFC (kg/N/h)")(iEngine)) / 3600, ...
        "ExhaustGasTemperatureMax_K", localCelsiusToKelvin(rawEngines.("EGT max (C)")(iEngine)), ...
        "ExhaustGasTemperatureContinuous_K", localCelsiusToKelvin(rawEngines.("EGT cont (C)")(iEngine)), ...
        "ElectricalPower_W", localNumber(rawEngines.("electrical (W)")(iEngine)), ...
        "SupplyVoltage_V", localNumber(rawEngines.("supply (V)")(iEngine)), ...
        "TimeBetweenOverhaul_s", localNumber(rawEngines.("TBO (h)")(iEngine)) * 3600, ...
        "MaxAltitude_m", localNumber(rawEngines.("max alt (m)")(iEngine)), ...
        "MaxMach", localNumber(rawEngines.("max speed (Mach)")(iEngine)), ...
        "StartEnvelopeAltitude_m", localNumber(rawEngines.("start envelope alt (m)")(iEngine)), ...
        "Lube", string(rawEngines.lube(iEngine)), ...
        "Fuel", string(rawEngines.fuel(iEngine)), ...
        "Notes", "");
end
end

function engine = localEmptyEngine()
engine = struct( ...
    "Option", NaN, ...
    "Name", "", ...
    "Type", "", ...
    "Architecture", "", ...
    "MaxThrust_N", NaN, ...
    "InstalledThrust_N", NaN, ...
    "IdleThrust_N", NaN, ...
    "SeaLevelStaticThrust_N", NaN, ...
    "InstalledSeaLevelStaticThrust_N", NaN, ...
    "DryMass_kg", NaN, ...
    "InstalledMass_kg", NaN, ...
    "ThrustToWeightEngineOnly", NaN, ...
    "OuterDiameter_m", NaN, ...
    "Length_m", NaN, ...
    "MaxAngularSpeed_rad_s", NaN, ...
    "IdleAngularSpeed_rad_s", NaN, ...
    "OverallPressureRatio", NaN, ...
    "ReferenceMassFlow_kg_s", NaN, ...
    "FuelFlow_kg_s", NaN, ...
    "SFC_kg_N_s", NaN, ...
    "ExhaustGasTemperatureMax_K", NaN, ...
    "ExhaustGasTemperatureContinuous_K", NaN, ...
    "ElectricalPower_W", NaN, ...
    "SupplyVoltage_V", NaN, ...
    "TimeBetweenOverhaul_s", NaN, ...
    "MaxAltitude_m", NaN, ...
    "MaxMach", NaN, ...
    "StartEnvelopeAltitude_m", NaN, ...
    "Lube", "", ...
    "Fuel", "", ...
    "Notes", "");
end

function value = localNumber(rawValue)
if ismissing(rawValue)
    value = NaN;
    return;
end

if isnumeric(rawValue)
    value = double(rawValue);
    return;
end

textValue = erase(strtrim(string(rawValue)), ",");
if textValue == ""
    value = NaN;
else
    value = str2double(textValue);
end
end

function angularSpeed_rad_s = localRpmToRadPerSec(rawRpm)
angularSpeed_rad_s = localNumber(rawRpm) * 2 * pi / 60;
end

function temperature_K = localCelsiusToKelvin(rawTemperature_C)
temperature_C = localNumber(rawTemperature_C);
if isnan(temperature_C)
    temperature_K = NaN;
else
    temperature_K = temperature_C + 273.15;
end
end
