function plotThrustDragComparison(results, dragResults)
%PLOTTHRUSTDRAGCOMPARISON Plot each engine thrust with its vehicle drag.
% Each engine/airframe pair gets its own figure.

arguments
    results (1,:) struct
    dragResults (1,:) struct
end

if numel(results) ~= numel(dragResults)
    error("plotThrustDragComparison:PairCountMismatch", ...
        "Engine results and drag results must have the same length.");
end

for iPair = 1:numel(results)
    localPlotPair(results(iPair), dragResults(iPair));
end
end

function localPlotPair(engineResult, dragResult)
figureName = "Thrust and Drag: " + engineResult.Name;
figureHandle = figure("Name", figureName, "Color", "w");
axesHandle = axes("Parent", figureHandle, "Position", [0.08 0.12 0.68 0.80]);
hold(axesHandle, "on");

colors = lines(2);
surfaceHandles = gobjects(1, 2);
surfaceNames = ["Thrust: " + engineResult.Name, ...
    "Drag: " + dragResult.Vehicle.EngineName];

[machMesh, altitudeMesh_m] = meshgrid(engineResult.Mach, engineResult.Altitude_m);
surfaceHandles(1) = surf( ...
    axesHandle, ...
    machMesh, ...
    altitudeMesh_m ./ 1000, ...
    engineResult.Thrust_N ./ 1000, ...
    "FaceColor", colors(1, :), ...
    "FaceAlpha", 0.60, ...
    "EdgeColor", "none", ...
    "DisplayName", surfaceNames(1));

[machMesh, altitudeMesh_m] = meshgrid(dragResult.Mach, dragResult.Altitude_m);
surfaceHandles(2) = surf( ...
    axesHandle, ...
    machMesh, ...
    altitudeMesh_m ./ 1000, ...
    dragResult.Drag_N ./ 1000, ...
    "FaceColor", colors(2, :), ...
    "FaceAlpha", 0.72, ...
    "EdgeColor", "none", ...
    "DisplayName", surfaceNames(2));

grid(axesHandle, "on");
box(axesHandle, "on");
view(axesHandle, 135, 28);
colormap(axesHandle, colors);
legend(axesHandle, "Location", "northeast", "Interpreter", "none");
rotate3d(figureHandle, "on");

title(axesHandle, engineResult.Name + " Thrust vs Vehicle Drag", ...
    "Interpreter", "none");
xlabel(axesHandle, "Mach Number");
ylabel(axesHandle, "Altitude, km");
zlabel(axesHandle, "Force, kN");

controlPanel = uipanel( ...
    "Parent", figureHandle, ...
    "Title", "Show surfaces", ...
    "Units", "normalized", ...
    "Position", [0.78 0.12 0.20 0.80]);

checkboxHeight = 0.14;

for iSurface = 1:numel(surfaceHandles)
    yPosition = 0.90 - iSurface * checkboxHeight;
    uicontrol( ...
        "Parent", controlPanel, ...
        "Style", "checkbox", ...
        "String", surfaceNames(iSurface), ...
        "Value", 1, ...
        "Units", "normalized", ...
        "Position", [0.08 yPosition 0.88 checkboxHeight], ...
        "Callback", @(source, ~) localSetVisibility(source, surfaceHandles(iSurface)));
end
end

function localSetVisibility(source, surfaceHandle)
if source.Value
    surfaceHandle.Visible = "on";
else
    surfaceHandle.Visible = "off";
end
end
