function atmosphere = standardAtmosphere(altitude_m)
%STANDARDATMOSPHERE Simple ISA atmosphere through the lower stratosphere.
% Valid for preliminary scaffold work up to 25 km.

arguments
    altitude_m (:,1) double {mustBeNonnegative}
end

g0 = 9.80665;
R = 287.05287;
gamma = 1.4;

T0 = 288.15;
p0 = 101325;
rho0 = 1.225;
lapseRate_K_m = -0.0065;
tropopause_m = 11000;

temperature_K = zeros(size(altitude_m));
pressure_Pa = zeros(size(altitude_m));
density_kg_m3 = zeros(size(altitude_m));

troposphereMask = altitude_m <= tropopause_m;
stratosphereMask = ~troposphereMask;

hTroposphere = altitude_m(troposphereMask);
temperature_K(troposphereMask) = T0 + lapseRate_K_m .* hTroposphere;
pressure_Pa(troposphereMask) = p0 .* ...
    (temperature_K(troposphereMask) ./ T0).^(-g0 / (lapseRate_K_m * R));
density_kg_m3(troposphereMask) = rho0 .* ...
    (temperature_K(troposphereMask) ./ T0).^((-g0 / (lapseRate_K_m * R)) - 1);

temperatureTropopause_K = T0 + lapseRate_K_m * tropopause_m;
pressureTropopause_Pa = p0 * ...
    (temperatureTropopause_K / T0)^(-g0 / (lapseRate_K_m * R));

hStratosphere = altitude_m(stratosphereMask);
temperature_K(stratosphereMask) = temperatureTropopause_K;
pressure_Pa(stratosphereMask) = pressureTropopause_Pa .* ...
    exp(-g0 .* (hStratosphere - tropopause_m) ./ (R * temperatureTropopause_K));
density_kg_m3(stratosphereMask) = pressure_Pa(stratosphereMask) ./ ...
    (R * temperatureTropopause_K);

speedOfSound_m_s = sqrt(gamma * R .* temperature_K);
dynamicViscosity_kg_m_s = 1.458e-6 .* temperature_K.^1.5 ./ ...
    (temperature_K + 110.4);
kinematicViscosity_m2_s = dynamicViscosity_kg_m_s ./ density_kg_m3;

atmosphere = table( ...
    altitude_m, ...
    temperature_K, ...
    pressure_Pa, ...
    density_kg_m3, ...
    speedOfSound_m_s, ...
    dynamicViscosity_kg_m_s, ...
    kinematicViscosity_m2_s, ...
    'VariableNames', [ ...
        "Altitude_m", ...
        "Temperature_K", ...
        "Pressure_Pa", ...
        "Density_kg_m3", ...
        "SpeedOfSound_m_s", ...
        "DynamicViscosity_kg_m_s", ...
        "KinematicViscosity_m2_s"]);
end
