function dragResults = evaluateVehicleDrag(vehicles, machGrid, altitudeGrid_m)
%EVALUATEVEHICLEDRAG Estimate first-cut drag polar over Mach/altitude.
% C_D = C_D0,skin + C_D_i + C_D_w,wing + C_D_w,volume.
% S_ref is the wing planform area.

arguments
    vehicles (1,:) struct
    machGrid (1,:) double {mustBeNonnegative}
    altitudeGrid_m (1,:) double {mustBeNonnegative}
end

dragResults = repmat(localEmptyDragResult(), 1, numel(vehicles));

for iVehicle = 1:numel(vehicles)
    dragResults(iVehicle) = localEvaluateOneVehicle( ...
        vehicles(iVehicle), machGrid, altitudeGrid_m);
end
end

function dragResult = localEvaluateOneVehicle(vehicle, machGrid, altitudeGrid_m)
atmosphere = standardAtmosphere(altitudeGrid_m(:));
[machMesh, ~] = meshgrid(machGrid, altitudeGrid_m);

densityMap_kg_m3 = repmat(atmosphere.Density_kg_m3, 1, numel(machGrid));
speedOfSoundMap_m_s = repmat(atmosphere.SpeedOfSound_m_s, 1, numel(machGrid));
kinematicViscosityMap_m2_s = repmat( ...
    atmosphere.KinematicViscosity_m2_s, 1, numel(machGrid));

trueAirspeed_m_s = machMesh .* speedOfSoundMap_m_s;
dynamicPressure_Pa = 0.5 .* densityMap_kg_m3 .* trueAirspeed_m_s.^2;

sRef_m2 = vehicle.ReferenceArea_m2;
weight_N = vehicle.GrossMass_kg * 9.80665;

wingReynoldsNumber = localReynoldsNumber( ...
    trueAirspeed_m_s, vehicle.MeanAerodynamicChord_m, ...
    kinematicViscosityMap_m2_s);
fuselageReynoldsNumber = localReynoldsNumber( ...
    trueAirspeed_m_s, vehicle.FuselageLength_m, ...
    kinematicViscosityMap_m2_s);

wingSkinFrictionCoefficient = localRaymerCompressibleSkinFriction( ...
    wingReynoldsNumber, machMesh);
fuselageSkinFrictionCoefficient = localRaymerCompressibleSkinFriction( ...
    fuselageReynoldsNumber, machMesh);

wingFormFactor = localWingFormFactor(vehicle, machMesh);
fuselageFormFactor = 1 + 60 / vehicle.FuselageFinenessRatio^3 + ...
    0.0025 * vehicle.FuselageFinenessRatio;

wingSkinDragCoefficient = wingSkinFrictionCoefficient .* wingFormFactor .* ...
    vehicle.WingInterferenceFactor .* vehicle.WingWettedArea_m2 ./ sRef_m2;
fuselageSkinDragCoefficient = fuselageSkinFrictionCoefficient .* ...
    fuselageFormFactor .* vehicle.FuselageInterferenceFactor .* ...
    vehicle.FuselageWettedArea_m2 ./ sRef_m2;
skinDragCoefficient = wingSkinDragCoefficient + fuselageSkinDragCoefficient;

liftCoefficient = weight_N ./ (dynamicPressure_Pa .* sRef_m2);
liftCoefficient(dynamicPressure_Pa <= 0) = NaN;

inducedDragCoefficient = liftCoefficient.^2 ./ ...
    (pi * vehicle.AspectRatio * vehicle.OswaldEfficiency);
wingWaveDragCoefficient = localWingWaveDragCoefficient( ...
    vehicle, machMesh, liftCoefficient, sRef_m2);
volumeWaveDragCoefficient = localSearsHaackVolumeWaveDragCoefficient( ...
    vehicle, machMesh, sRef_m2);

totalDragCoefficient = skinDragCoefficient + inducedDragCoefficient + ...
    wingWaveDragCoefficient + volumeWaveDragCoefficient;
drag_N = dynamicPressure_Pa .* sRef_m2 .* totalDragCoefficient;

dragResult = struct( ...
    "Name", vehicle.Name, ...
    "Vehicle", vehicle, ...
    "Mach", machGrid, ...
    "Altitude_m", altitudeGrid_m, ...
    "Atmosphere", atmosphere, ...
    "TrueAirspeed_m_s", trueAirspeed_m_s, ...
    "DynamicPressure_Pa", dynamicPressure_Pa, ...
    "LiftCoefficient", liftCoefficient, ...
    "WingReynoldsNumber", wingReynoldsNumber, ...
    "FuselageReynoldsNumber", fuselageReynoldsNumber, ...
    "WingSkinFrictionCoefficient", wingSkinFrictionCoefficient, ...
    "FuselageSkinFrictionCoefficient", fuselageSkinFrictionCoefficient, ...
    "WingSkinDragCoefficient", wingSkinDragCoefficient, ...
    "FuselageSkinDragCoefficient", fuselageSkinDragCoefficient, ...
    "SkinDragCoefficient", skinDragCoefficient, ...
    "InducedDragCoefficient", inducedDragCoefficient, ...
    "WingWaveDragCoefficient", wingWaveDragCoefficient, ...
    "VolumeWaveDragCoefficient", volumeWaveDragCoefficient, ...
    "TotalDragCoefficient", totalDragCoefficient, ...
    "Drag_N", drag_N, ...
    "ModelParameters", struct( ...
        "ReferenceArea_m2", sRef_m2, ...
        "Weight_N", weight_N, ...
        "InducedDragBasis", "steady level flight CL = W / qS", ...
        "SkinFrictionBasis", "Raymer turbulent compressible flat plate", ...
        "WingWaveBasis", "Korn-style critical Mach estimate", ...
        "VolumeWaveBasis", "Sears-Haack body wave drag area"));
end

function reynoldsNumber = localReynoldsNumber(velocity_m_s, length_m, nu_m2_s)
reynoldsNumber = velocity_m_s .* length_m ./ nu_m2_s;
reynoldsNumber(reynoldsNumber < 1) = NaN;
end

function cf = localRaymerCompressibleSkinFriction(reynoldsNumber, mach)
cf = 0.455 ./ ((log10(reynoldsNumber)).^2.58 .* ...
    (1 + 0.144 .* mach.^2).^0.65);
end

function formFactor = localWingFormFactor(vehicle, mach)
thicknessToChord = vehicle.WingThicknessToChord;
maxThicknessLocation = vehicle.WingMaxThicknessLocationChord;

formFactor = (1 + 0.6 / maxThicknessLocation * thicknessToChord + ...
    100 * thicknessToChord^4) .* (1.34 .* max(mach, 0.001).^0.18);
end

function cdWaveWing = localWingWaveDragCoefficient( ...
    vehicle, mach, liftCoefficient, sRef_m2)
criticalMach = localKornCriticalMach(vehicle, liftCoefficient);
denominator = max(1 - criticalMach, 0.05);
waveRise = max(0, (mach - criticalMach) ./ denominator);

cdWaveExposedWing = vehicle.WingWaveDragScale .* ...
    vehicle.WingThicknessToChord^2 .* waveRise.^4;
cdWaveWing = cdWaveExposedWing .* vehicle.WingExposedArea_m2 ./ sRef_m2;
end

function criticalMach = localKornCriticalMach(vehicle, liftCoefficient)
cosSweep = cos(vehicle.WingQuarterChordSweep_rad);
technologyFactor = 0.87;
sectionCriticalMach = technologyFactor - ...
    vehicle.WingThicknessToChord ./ cosSweep - ...
    liftCoefficient ./ (10 * cosSweep^3);
criticalMach = sectionCriticalMach ./ cosSweep;
criticalMach = min(max(criticalMach, 0.10), 0.98);
end

function cdWaveVolume = localSearsHaackVolumeWaveDragCoefficient( ...
    vehicle, mach, sRef_m2)
length_m = vehicle.FuselageLength_m;
volume_m3 = (2 / 3) * vehicle.FuselageFrontalArea_m2 * length_m;

waveDragArea_m2 = (9 * pi^3 / 2) * volume_m3^2 / length_m^4;
supersonicRamp = min(max((mach - 1.0) ./ 0.20, 0), 1).^2;
cdWaveVolume = waveDragArea_m2 / sRef_m2 .* supersonicRamp;
end

function dragResult = localEmptyDragResult()
dragResult = struct( ...
    "Name", "", ...
    "Vehicle", struct(), ...
    "Mach", [], ...
    "Altitude_m", [], ...
    "Atmosphere", table(), ...
    "TrueAirspeed_m_s", [], ...
    "DynamicPressure_Pa", [], ...
    "LiftCoefficient", [], ...
    "WingReynoldsNumber", [], ...
    "FuselageReynoldsNumber", [], ...
    "WingSkinFrictionCoefficient", [], ...
    "FuselageSkinFrictionCoefficient", [], ...
    "WingSkinDragCoefficient", [], ...
    "FuselageSkinDragCoefficient", [], ...
    "SkinDragCoefficient", [], ...
    "InducedDragCoefficient", [], ...
    "WingWaveDragCoefficient", [], ...
    "VolumeWaveDragCoefficient", [], ...
    "TotalDragCoefficient", [], ...
    "Drag_N", [], ...
    "ModelParameters", struct());
end
