function dragResults = evaluateVehicleDrag(vehicles, machGrid, altitudeGrid_m)
%EVALUATEVEHICLEDRAG Level-flight drag over Mach and altitude.
% C_D = C_D,skin + C_D,i + C_D,wave,wing + C_D,wave,volume.
% Skin friction is the Raymer turbulent plate, with a tail and an
% excrescence factor. Wing wave drag is a Lock rise from Korn drag-divergence
% Mach, capped so it stays finite through Mach 1.1. Volume wave drag is
% WaveDragFactor times the Sears-Haack minimum of the fuselage-plus-wing
% volume, faired in across the transonic range. S_ref is the wing planform.

arguments
    vehicles (1,:) struct
    machGrid (1,:) double {mustBeNonnegative}
    altitudeGrid_m (1,:) double {mustBeNonnegative}
end

dragResults = repmat(localEmptyDragResult(), 1, numel(vehicles));

for iVehicle = 1:numel(vehicles)
    dragResults(iVehicle) = localEvaluateOneVehicle( ...
        vehicles(iVehicle), machGrid, altitudeGrid_m);
end
end

function dragResult = localEvaluateOneVehicle(vehicle, machGrid, altitudeGrid_m)
atmosphere = standardAtmosphere(altitudeGrid_m(:));
[machMesh, ~] = meshgrid(machGrid, altitudeGrid_m);

densityMap_kg_m3 = repmat(atmosphere.Density_kg_m3, 1, numel(machGrid));
speedOfSoundMap_m_s = repmat(atmosphere.SpeedOfSound_m_s, 1, numel(machGrid));
kinematicViscosityMap_m2_s = repmat( ...
    atmosphere.KinematicViscosity_m2_s, 1, numel(machGrid));

trueAirspeed_m_s = machMesh .* speedOfSoundMap_m_s;
dynamicPressure_Pa = 0.5 .* densityMap_kg_m3 .* trueAirspeed_m_s.^2;

sRef_m2 = vehicle.ReferenceArea_m2;
weight_N = vehicle.GrossMass_kg * 9.80665;

wingReynoldsNumber = localReynoldsNumber( ...
    trueAirspeed_m_s, vehicle.MeanAerodynamicChord_m, ...
    kinematicViscosityMap_m2_s);
fuselageReynoldsNumber = localReynoldsNumber( ...
    trueAirspeed_m_s, vehicle.FuselageLength_m, ...
    kinematicViscosityMap_m2_s);
tailReynoldsNumber = localReynoldsNumber( ...
    trueAirspeed_m_s, vehicle.TailChord_m, ...
    kinematicViscosityMap_m2_s);

wingSkinFrictionCoefficient = localRaymerCompressibleSkinFriction( ...
    wingReynoldsNumber, machMesh);
fuselageSkinFrictionCoefficient = localRaymerCompressibleSkinFriction( ...
    fuselageReynoldsNumber, machMesh);
tailSkinFrictionCoefficient = localRaymerCompressibleSkinFriction( ...
    tailReynoldsNumber, machMesh);

wingFormFactor = localSurfaceFormFactor( ...
    vehicle.WingThicknessToChord, vehicle.WingMaxThicknessLocationChord, ...
    vehicle.WingMaxThicknessSweep_rad, machMesh, vehicle.FormFactorMachCap);
tailFormFactor = localSurfaceFormFactor( ...
    vehicle.TailThicknessToChord, vehicle.TailMaxThicknessLocationChord, ...
    vehicle.TailMaxThicknessSweep_rad, machMesh, vehicle.FormFactorMachCap);
fuselageFormFactor = localFuselageFormFactor(vehicle.FuselageFinenessRatio);

excrescence = vehicle.ExcrescenceFactor;
wingSkinDragCoefficient = excrescence .* wingSkinFrictionCoefficient .* ...
    wingFormFactor .* vehicle.WingInterferenceFactor .* ...
    vehicle.WingWettedArea_m2 ./ sRef_m2;
fuselageSkinDragCoefficient = excrescence .* ...
    fuselageSkinFrictionCoefficient .* fuselageFormFactor .* ...
    vehicle.FuselageInterferenceFactor .* ...
    vehicle.FuselageWettedArea_m2 ./ sRef_m2;
tailSkinDragCoefficient = excrescence .* tailSkinFrictionCoefficient .* ...
    tailFormFactor .* vehicle.TailInterferenceFactor .* ...
    vehicle.TailWettedArea_m2 ./ sRef_m2;
skinDragCoefficient = wingSkinDragCoefficient + ...
    fuselageSkinDragCoefficient + tailSkinDragCoefficient;

liftCoefficient = weight_N ./ (dynamicPressure_Pa .* sRef_m2);
liftCoefficient(dynamicPressure_Pa <= 0) = NaN;

inducedDragCoefficient = liftCoefficient.^2 ./ ...
    (pi * vehicle.AspectRatio * vehicle.OswaldEfficiency);
[wingWaveDragCoefficient, dragDivergenceMach] = ...
    localWingWaveDragCoefficient(vehicle, machMesh, liftCoefficient, sRef_m2);
[volumeWaveDragCoefficient, waveDragArea_m2] = ...
    localVolumeWaveDragCoefficient(vehicle, machMesh, sRef_m2);

totalDragCoefficient = skinDragCoefficient + inducedDragCoefficient + ...
    wingWaveDragCoefficient + volumeWaveDragCoefficient;
drag_N = dynamicPressure_Pa .* sRef_m2 .* totalDragCoefficient;

dragResult = struct( ...
    "Name", vehicle.Name, ...
    "Vehicle", vehicle, ...
    "Mach", machGrid, ...
    "Altitude_m", altitudeGrid_m, ...
    "Atmosphere", atmosphere, ...
    "TrueAirspeed_m_s", trueAirspeed_m_s, ...
    "DynamicPressure_Pa", dynamicPressure_Pa, ...
    "LiftCoefficient", liftCoefficient, ...
    "WingReynoldsNumber", wingReynoldsNumber, ...
    "FuselageReynoldsNumber", fuselageReynoldsNumber, ...
    "TailReynoldsNumber", tailReynoldsNumber, ...
    "WingSkinFrictionCoefficient", wingSkinFrictionCoefficient, ...
    "FuselageSkinFrictionCoefficient", fuselageSkinFrictionCoefficient, ...
    "TailSkinFrictionCoefficient", tailSkinFrictionCoefficient, ...
    "WingSkinDragCoefficient", wingSkinDragCoefficient, ...
    "FuselageSkinDragCoefficient", fuselageSkinDragCoefficient, ...
    "TailSkinDragCoefficient", tailSkinDragCoefficient, ...
    "SkinDragCoefficient", skinDragCoefficient, ...
    "InducedDragCoefficient", inducedDragCoefficient, ...
    "WingWaveDragCoefficient", wingWaveDragCoefficient, ...
    "VolumeWaveDragCoefficient", volumeWaveDragCoefficient, ...
    "KornDragDivergenceMach", dragDivergenceMach, ...
    "TotalDragCoefficient", totalDragCoefficient, ...
    "Drag_N", drag_N, ...
    "ModelParameters", struct( ...
        "ReferenceArea_m2", sRef_m2, ...
        "Weight_N", weight_N, ...
        "GrossMass_kg", vehicle.GrossMass_kg, ...
        "MeanAerodynamicChord_m", vehicle.MeanAerodynamicChord_m, ...
        "WingQuarterChordSweep_deg", vehicle.WingQuarterChordSweep_deg, ...
        "AsymptoticWaveDragArea_m2", waveDragArea_m2, ...
        "AsymptoticVolumeWaveDragCoefficient", waveDragArea_m2 / sRef_m2, ...
        "InducedDragBasis", "steady level flight CL = W / qS", ...
        "SkinFrictionBasis", "Raymer turbulent plate plus tail and excrescence", ...
        "WingWaveBasis", "Korn drag divergence with a capped Lock rise", ...
        "VolumeWaveBasis", "WaveDragFactor times Sears-Haack of fuselage plus wing volume"));
end

function reynoldsNumber = localReynoldsNumber(velocity_m_s, length_m, nu_m2_s)
reynoldsNumber = velocity_m_s .* length_m ./ nu_m2_s;
reynoldsNumber(reynoldsNumber < 1) = NaN;
end

function cf = localRaymerCompressibleSkinFriction(reynoldsNumber, mach)
cf = 0.455 ./ ((log10(reynoldsNumber)).^2.58 .* ...
    (1 + 0.144 .* mach.^2).^0.65);
end

function formFactor = localSurfaceFormFactor( ...
    thicknessToChord, maxThicknessLocation, sweep_rad, mach, machCap)
machUse = min(max(mach, 0.25), machCap);
cosSweep = max(cos(sweep_rad), 0.25);
incompressible = 1 + 0.6 / maxThicknessLocation * thicknessToChord + ...
    100 * thicknessToChord^4;
formFactor = incompressible .* (1.34 .* machUse.^0.18 .* cosSweep.^0.28);
end

function formFactor = localFuselageFormFactor(finenessRatio)
fineness = max(finenessRatio, 1);
formFactor = 1 + 60 / fineness^3 + 0.0025 * fineness;
end

function [cdWaveWing, dragDivergenceMach] = localWingWaveDragCoefficient( ...
    vehicle, mach, liftCoefficient, sRef_m2)
dragDivergenceMach = localKornDragDivergenceMach(vehicle, liftCoefficient);
criticalMach = dragDivergenceMach - vehicle.DragCreepMachOffset;
deltaMach = max(0, mach - criticalMach);
cdLock = vehicle.LockRiseCoefficient .* deltaMach.^4;

cosSweep = max(cos(vehicle.WingQuarterChordSweep_rad), 0.25);
cdCap = vehicle.WingWaveDragCapFactor * vehicle.WingThicknessToChord^2 * ...
    cosSweep^2;

cdSection = zeros(size(mach));
active = isfinite(cdLock) & cdLock > 0 & cdCap > 0;
cdSection(active) = (cdLock(active) .* cdCap) ./ (cdLock(active) + cdCap);
cdWaveWing = cdSection .* vehicle.WingExposedArea_m2 ./ sRef_m2;
end

function dragDivergenceMach = localKornDragDivergenceMach(vehicle, liftCoefficient)
cosSweep = max(cos(vehicle.WingQuarterChordSweep_rad), 0.25);
dragDivergenceMach = vehicle.KornTechnologyFactor ./ cosSweep - ...
    vehicle.WingThicknessToChord ./ cosSweep.^2 - ...
    liftCoefficient ./ (10 * cosSweep.^3);
dragDivergenceMach = min(max(dragDivergenceMach, 0.30), 1.80);
dragDivergenceMach(~isfinite(liftCoefficient)) = NaN;
end

function [cdWaveVolume, waveDragArea_m2] = localVolumeWaveDragCoefficient( ...
    vehicle, mach, sRef_m2)
equivalentVolume_m3 = vehicle.FuselageVolume_m3 + vehicle.WingVolume_m3;
length_m = vehicle.FuselageLength_m;
% Sears-Haack minimum drag area for a given length and volume.
waveDragArea_m2 = vehicle.WaveDragFactor * (128 / pi) * ...
    equivalentVolume_m3^2 / length_m^4;

fineness = max(vehicle.FuselageFinenessRatio, 1);
machStart = 1 - vehicle.VolumeWaveOnsetNumerator / fineness;
machStart = min(max(machStart, 0.70), 0.95);
machFull = max(vehicle.VolumeWaveMachFull, machStart + 0.05);
ramp = localSmoothstep((mach - machStart) ./ (machFull - machStart));
cdWaveVolume = waveDragArea_m2 / sRef_m2 .* ramp;
end

function y = localSmoothstep(x)
x = min(max(x, 0), 1);
y = x.^2 .* (3 - 2 .* x);
end

function dragResult = localEmptyDragResult()
dragResult = struct( ...
    "Name", "", ...
    "Vehicle", struct(), ...
    "Mach", [], ...
    "Altitude_m", [], ...
    "Atmosphere", table(), ...
    "TrueAirspeed_m_s", [], ...
    "DynamicPressure_Pa", [], ...
    "LiftCoefficient", [], ...
    "WingReynoldsNumber", [], ...
    "FuselageReynoldsNumber", [], ...
    "TailReynoldsNumber", [], ...
    "WingSkinFrictionCoefficient", [], ...
    "FuselageSkinFrictionCoefficient", [], ...
    "TailSkinFrictionCoefficient", [], ...
    "WingSkinDragCoefficient", [], ...
    "FuselageSkinDragCoefficient", [], ...
    "TailSkinDragCoefficient", [], ...
    "SkinDragCoefficient", [], ...
    "InducedDragCoefficient", [], ...
    "WingWaveDragCoefficient", [], ...
    "VolumeWaveDragCoefficient", [], ...
    "KornDragDivergenceMach", [], ...
    "TotalDragCoefficient", [], ...
    "Drag_N", [], ...
    "ModelParameters", struct());
end
